// Mocks generated by Mockito 5.4.5 from annotations
// in flower_ecommerce_app_team5/test/modules/authentication/data/data_sources_imp/login_as_guest/login_as_guest_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_ecommerce_app_team5/shared_layers/storage/contracts/flutter_secure_storage_service_contract.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService<T> extends _i1.Mock
    implements _i2.SecureStorageService<T> {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setStringValue(
    String? key,
    String? value, [
    String? widgetName = '',
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setStringValue,
          [
            key,
            value,
            widgetName,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<String?> getStringValue(
    String? key, [
    String? widgetName = '',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStringValue,
          [
            key,
            widgetName,
          ],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> deleteValue(
    String? key, [
    String? widgetName = '',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteValue,
          [
            key,
            widgetName,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
