// Mocks generated by Mockito 5.4.4 from annotations
// in flower_ecommerce_app_team5/test/modules/home/data/datasource_impl/home_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flower_ecommerce_app_team5/modules/home/data/api/api_client/home_api_client.dart'
    as _i7;
import 'package:flower_ecommerce_app_team5/modules/home/data/models/all_gategories_reponse/all_categories_response.dart'
    as _i2;
import 'package:flower_ecommerce_app_team5/modules/home/data/models/all_occasions_response/all_occasions_response.dart'
    as _i3;
import 'package:flower_ecommerce_app_team5/modules/home/data/models/all_products_response/all_product_response.dart'
    as _i5;
import 'package:flower_ecommerce_app_team5/modules/home/data/models/cart_response/add_to_cart_request.dart'
    as _i9;
import 'package:flower_ecommerce_app_team5/modules/home/data/models/cart_response/cart_response_model.dart'
    as _i6;
import 'package:flower_ecommerce_app_team5/modules/home/data/models/home_data_response/home_data_response.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAllCategoriesResponse_0 extends _i1.SmartFake
    implements _i2.AllCategoriesResponse {
  _FakeAllCategoriesResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAllOccasionsResponse_1 extends _i1.SmartFake
    implements _i3.AllOccasionsResponse {
  _FakeAllOccasionsResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHomeDataResponse_2 extends _i1.SmartFake
    implements _i4.HomeDataResponse {
  _FakeHomeDataResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAllProductResponse_3 extends _i1.SmartFake
    implements _i5.AllProductResponse {
  _FakeAllProductResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCartResponse_4 extends _i1.SmartFake implements _i6.CartResponse {
  _FakeCartResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeApiClient extends _i1.Mock implements _i7.HomeApiClient {
  MockHomeApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.AllCategoriesResponse> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i8.Future<_i2.AllCategoriesResponse>.value(
            _FakeAllCategoriesResponse_0(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i8.Future<_i2.AllCategoriesResponse>);

  @override
  _i8.Future<_i3.AllOccasionsResponse> getOccasions() => (super.noSuchMethod(
        Invocation.method(
          #getOccasions,
          [],
        ),
        returnValue: _i8.Future<_i3.AllOccasionsResponse>.value(
            _FakeAllOccasionsResponse_1(
          this,
          Invocation.method(
            #getOccasions,
            [],
          ),
        )),
      ) as _i8.Future<_i3.AllOccasionsResponse>);

  @override
  _i8.Future<_i4.HomeDataResponse> getHomeData() => (super.noSuchMethod(
        Invocation.method(
          #getHomeData,
          [],
        ),
        returnValue:
            _i8.Future<_i4.HomeDataResponse>.value(_FakeHomeDataResponse_2(
          this,
          Invocation.method(
            #getHomeData,
            [],
          ),
        )),
      ) as _i8.Future<_i4.HomeDataResponse>);

  @override
  _i8.Future<_i5.AllProductResponse> getAllProduct({String? categoryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllProduct,
          [],
          {#categoryId: categoryId},
        ),
        returnValue:
            _i8.Future<_i5.AllProductResponse>.value(_FakeAllProductResponse_3(
          this,
          Invocation.method(
            #getAllProduct,
            [],
            {#categoryId: categoryId},
          ),
        )),
      ) as _i8.Future<_i5.AllProductResponse>);

  @override
  _i8.Future<_i6.CartResponse> getCartItems() => (super.noSuchMethod(
        Invocation.method(
          #getCartItems,
          [],
        ),
        returnValue: _i8.Future<_i6.CartResponse>.value(_FakeCartResponse_4(
          this,
          Invocation.method(
            #getCartItems,
            [],
          ),
        )),
      ) as _i8.Future<_i6.CartResponse>);

  @override
  _i8.Future<_i6.CartResponse> addToCart(
          _i9.AddToCartRequest? addToCartRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToCart,
          [addToCartRequest],
        ),
        returnValue: _i8.Future<_i6.CartResponse>.value(_FakeCartResponse_4(
          this,
          Invocation.method(
            #addToCart,
            [addToCartRequest],
          ),
        )),
      ) as _i8.Future<_i6.CartResponse>);

  @override
  _i8.Future<_i6.CartResponse> deleteFromCart(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFromCart,
          [productId],
        ),
        returnValue: _i8.Future<_i6.CartResponse>.value(_FakeCartResponse_4(
          this,
          Invocation.method(
            #deleteFromCart,
            [productId],
          ),
        )),
      ) as _i8.Future<_i6.CartResponse>);
}
