name: flower_ecommerce_app_team5
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3  # Updated for null safety

dependencies:
  flutter:
    sdk: flutter

  # native splash
  flutter_native_splash: ^2.3.3

  # localization
  easy_localization: ^3.0.5
  # dependency injection
  injectable: ^2.1.2
  get_it: ^7.6.4

  # API dependencies
  retrofit: ^4.0.1
  dio: ^5.8.0+1
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.4.0

  # State Management
  provider: ^6.1.2
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0

  # Local Storage
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  custom_refresh_indicator: ^4.0.1
  smooth_page_indicator: ^1.2.1
  lottie: ^2.7.0

  # UI components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.5

  # Utilities
  meta: ^1.15.0
  equatable: ^2.0.7
  palette_generator: ^0.3.3+6
  path_provider: ^2.1.5
  http_parser: ^4.0.2

  # Device features
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  flutter_image_compress: ^2.4.0
  device_info_plus: ^11.3.0
  url_launcher: ^6.3.1

  # Testing & debugging
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4

  geocoding: ^3.0.0

  back_button_interceptor: ^8.0.4
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5
  auto_size_text: ^3.0.0
  flutter_timer_countdown: ^1.0.7
  otp_text_field: ^1.1.3
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  logger: ^2.5.0
  cloud_firestore: ^5.6.7
  intl: ^0.20.2
  timelines_plus: ^1.0.6
  timeline_tile: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build tools
  build_runner: ^2.4.4
  retrofit_generator: ^9.0.0
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.2
  easy_localization_generator: ^0.3.3  # Specific version that works with intl 0.20.2

  # Other dev tools
  flutter_launcher_icons: ^0.14.3

  # API dev_dependencies
  retrofit_generator: any # for Dart 3.3 use ^9.0.0
  build_runner: any
  json_serializable: any

  # dependency injection
  injectable_generator: any

  # localization dev_dependencies
#  easy_localization_generator: 1.0.0


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

dependency_overrides:
  intl: ^0.20.2  # Temporary override until all packages update

flutter:
  uses-material-design: true
  assets:
    - lib/shared_layers/localization/l10n_json_files/
    - assets/icons/
    - assets/animations/
    - assets/images/
    - assets/files/AboutUs.json
    - assets/files/Terms.json
    - assets/files/cities.json
    - assets/files/states.json
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
