// Mocks generated by Mockito 5.4.5 from annotations
// in flower_ecommerce_app_team5/test/modules/check_out/data/data_source_impl/checkout_data_souce_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flower_ecommerce_app_team5/modules/check_out/data/api/api_client/check_out_api_client.dart'
    as _i3;
import 'package:flower_ecommerce_app_team5/modules/check_out/data/models/address_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAddressResponse_0 extends _i1.SmartFake
    implements _i2.AddressResponse {
  _FakeAddressResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CheckOutApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckOutApiClient extends _i1.Mock implements _i3.CheckOutApiClient {
  MockCheckOutApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AddressResponse> getAllAddresses() => (super.noSuchMethod(
        Invocation.method(
          #getAllAddresses,
          [],
        ),
        returnValue:
            _i4.Future<_i2.AddressResponse>.value(_FakeAddressResponse_0(
          this,
          Invocation.method(
            #getAllAddresses,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AddressResponse>);
}
