// Mocks generated by Mockito 5.4.5 from annotations
// in flower_ecommerce_app_team5/test/modules/payment/data/data_source_imp/payment/payment_remote_data_source_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_ecommerce_app_team5/modules/payment/data/api/api_client/payment_api_client.dart'
    as _i4;
import 'package:flower_ecommerce_app_team5/modules/payment/data/models/cash_order_response/cash_order_response_dto.dart'
    as _i2;
import 'package:flower_ecommerce_app_team5/modules/payment/data/models/checkout_session_response/checkout_response_dto.dart'
    as _i3;
import 'package:flower_ecommerce_app_team5/modules/payment/data/models/payment_request_parameters/payment_request_parameters.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCashOrderResponseDto_0 extends _i1.SmartFake
    implements _i2.CashOrderResponseDto {
  _FakeCashOrderResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckoutResponseDto_1 extends _i1.SmartFake
    implements _i3.CheckoutResponseDto {
  _FakeCheckoutResponseDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PaymentApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentApiClient extends _i1.Mock implements _i4.PaymentApiClient {
  MockPaymentApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.CashOrderResponseDto> makeCashOrder(
          _i6.PaymentRequestParametersDto? paymentRequestParameters) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeCashOrder,
          [paymentRequestParameters],
        ),
        returnValue: _i5.Future<_i2.CashOrderResponseDto>.value(
            _FakeCashOrderResponseDto_0(
          this,
          Invocation.method(
            #makeCashOrder,
            [paymentRequestParameters],
          ),
        )),
      ) as _i5.Future<_i2.CashOrderResponseDto>);

  @override
  _i5.Future<_i3.CheckoutResponseDto> makeCheckoutSession(
          _i6.PaymentRequestParametersDto? paymentRequestParameters) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeCheckoutSession,
          [paymentRequestParameters],
        ),
        returnValue: _i5.Future<_i3.CheckoutResponseDto>.value(
            _FakeCheckoutResponseDto_1(
          this,
          Invocation.method(
            #makeCheckoutSession,
            [paymentRequestParameters],
          ),
        )),
      ) as _i5.Future<_i3.CheckoutResponseDto>);
}
