name: Branch Name Validation

on:
  pull_request:
    branches: ['**']  # Checks all branches (alternatively, specify protected branches like 'main')

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use v3 (latest)

      - name: Extract branch name
        id: extract-branch
        run: |
          echo "branch_name=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Validate branch name
        run: |
          chmod +x ./.github/scripts/validate_branch_name.sh
          ./.github/scripts/validate_branch_name.sh "${{ env.branch_name }}"
