// Mocks generated by Mockito 5.4.4 from annotations
// in flower_ecommerce_app_team5/test/modules/payment/domain/use_cases/payment/make_checkout_session_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_ecommerce_app_team5/core/apis/api_result/api_result.dart'
    as _i4;
import 'package:flower_ecommerce_app_team5/modules/payment/domain/entities/cash_order_response/cash_order_response_entity.dart'
    as _i5;
import 'package:flower_ecommerce_app_team5/modules/payment/domain/entities/checkout_session_response/checkout_response_entity.dart'
    as _i8;
import 'package:flower_ecommerce_app_team5/modules/payment/domain/entities/payment_request_parameters/payment_request_parameter_entity.dart'
    as _i6;
import 'package:flower_ecommerce_app_team5/modules/payment/domain/repository_contract/payment/payment_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i2.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.ApiResult<_i5.CashOrderResponseEntity>> makeCashOrder(
          {required _i6.PaymentRequestParametersEntity?
              paymentRequestParameters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeCashOrder,
          [],
          {#paymentRequestParameters: paymentRequestParameters},
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i5.CashOrderResponseEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i5.CashOrderResponseEntity>>(
          this,
          Invocation.method(
            #makeCashOrder,
            [],
            {#paymentRequestParameters: paymentRequestParameters},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i5.CashOrderResponseEntity>>);

  @override
  _i3.Future<_i4.ApiResult<_i8.CheckoutResponseEntity>> makeCheckoutSession(
          {required _i6.PaymentRequestParametersEntity?
              paymentRequestParameters}) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeCheckoutSession,
          [],
          {#paymentRequestParameters: paymentRequestParameters},
        ),
        returnValue:
            _i3.Future<_i4.ApiResult<_i8.CheckoutResponseEntity>>.value(
                _i7.dummyValue<_i4.ApiResult<_i8.CheckoutResponseEntity>>(
          this,
          Invocation.method(
            #makeCheckoutSession,
            [],
            {#paymentRequestParameters: paymentRequestParameters},
          ),
        )),
      ) as _i3.Future<_i4.ApiResult<_i8.CheckoutResponseEntity>>);
}
